# Build Stage
FROM golang:1.22-alpine AS builder

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . .

# Build the application
RUN CGO_ENABLED=0 GOOS=linux go build -o sentinel-server ./cmd/server

# Run Stage
FROM alpine:latest

WORKDIR /app

# Copy binary from builder
COPY --from=builder /app/sentinel-server .
# Copy Lua scripts (important!)
COPY --from=builder /app/redis ./redis

# Expose port
EXPOSE 8080

CMD ["./sentinel-server"]
